# *** This Dockefile is generated by KloverCloud *** #
FROM quay.io/klovercloud/golang:1.20 as builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /app/bin/naagaad .



FROM quay.io/klovercloud/golang:1.20

RUN useradd -ms /bin/bash klovercloud
WORKDIR /home/klovercloud

COPY --from=builder /app/bin .
COPY --from=builder /app/views ./views

EXPOSE 8080

USER klovercloud
CMD ["./naagaad"]
